name: Run main.py

on:
  schedule:
    - cron: '0 */2 * * *' # Hər 2 saatda bir işləyir
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Repo-nu yüklə
      - name: Checkout repository
        uses: actions/checkout@v4

      # Python-u quraşdır
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Konkret Python versiyası

      # Dependency-ləri yüklə
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Python skriptini işlə
      - name: Execute Python script
        run: |
          python main.py config.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Token əlavə et

      # Dəyişiklikləri commit və push et
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --quiet || git commit -m "Updated streams [skip ci]" # Dəyişiklik varsa commit et
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
